### ISSUE TITLE
Can we generate 2 files per table?

### ISSUE THREAD

**Issue by Surdok** [leonetosoft/ferreiro#1]
I seen your repo for generating the models for sequalize-ts, and it was impressive, and saved me alot of time, thank you very much :)

What I need is to generate type-graph-ql mutations per table, so I wouldn't have to write the mutations for each table if I am going to use type-graph_ql, so that the first file would contain the columns for graph-ql, and the second file would contain the mutations.

**Comment by leonetosoft** [comment]
sorry for the delay, but a lot happening at the same time.
I plan to spend more time.
How did you solve this problem? know that you can create a custom pattern....
Writing it on HBS

**Comment by leonetosoft** [comment]
Yes, repeat structure:

#begin_file
{{fileName '..... filename '}}
